# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fine_tune_SAM',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/fine_tune_SAM',
                'lib_path': 'fine_tune_SAM'},
  'syms': {'fine_tune_SAM.core': {'fine_tune_SAM.core.foo': ('core.html#foo', 'fine_tune_SAM/core.py')}}}
