# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fine_tune_SAM',
                'doc_host': 'https://HasanGoni.github.io',
                'git_url': 'https://github.com/HasanGoni/fine_tune_SAM',
                'lib_path': 'fine_tune_SAM'},
  'syms': { 'fine_tune_SAM.core': {'fine_tune_SAM.core.foo': ('core.html#foo', 'fine_tune_SAM/core.py')},
            'fine_tune_SAM.data_prep': {},
            'fine_tune_SAM.patch_dataset': { 'fine_tune_SAM.patch_dataset.patch_img_and_mask': ( 'patch_dataset.html#patch_img_and_mask',
                                                                                                 'fine_tune_SAM/patch_dataset.py'),
                                             'fine_tune_SAM.patch_dataset.show_rand_img': ( 'patch_dataset.html#show_rand_img',
                                                                                            'fine_tune_SAM/patch_dataset.py')}}}
