# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_inference_with_medSAM.ipynb.

# %% auto 0
__all__ = ['get_model']

# %% ../nbs/05_inference_with_medSAM.ipynb 3
import torch
from typing import List, Dict, Any, Union, Tuple
from transformers import SamModel, SamProcessor

# %% ../nbs/05_inference_with_medSAM.ipynb 4
def get_model(
        model_name:str,
        device:Union[str, None] = None
        
    ) -> SamModel:
    prcoessor = SamProcessor.from_pretrained(model_name)
    device = device if device else 'cuda' if torch.cuda.is_available() else 'cpu'
    model = SamModel.from_pretrained(model_name).to(device)
    return model
